name: Fetch Latest Data

on:
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send VERCEL Build Trigger
        run: curl ${{ env.VERCEL_WEBHOOK_URL }}
